#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enciclopedia_canina_store
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Can_Store")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcategoria(categoria instance);
    partial void Updatecategoria(categoria instance);
    partial void Deletecategoria(categoria instance);
    partial void Insertciudad(ciudad instance);
    partial void Updateciudad(ciudad instance);
    partial void Deleteciudad(ciudad instance);
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void InsertDetalle_Factura(Detalle_Factura instance);
    partial void UpdateDetalle_Factura(Detalle_Factura instance);
    partial void DeleteDetalle_Factura(Detalle_Factura instance);
    partial void Insertfabricante(fabricante instance);
    partial void Updatefabricante(fabricante instance);
    partial void Deletefabricante(fabricante instance);
    partial void Insertfac_ven_detalle(fac_ven_detalle instance);
    partial void Updatefac_ven_detalle(fac_ven_detalle instance);
    partial void Deletefac_ven_detalle(fac_ven_detalle instance);
    partial void InsertFactura_Reporte(Factura_Reporte instance);
    partial void UpdateFactura_Reporte(Factura_Reporte instance);
    partial void DeleteFactura_Reporte(Factura_Reporte instance);
    partial void Insertfactura_venta(factura_venta instance);
    partial void Updatefactura_venta(factura_venta instance);
    partial void Deletefactura_venta(factura_venta instance);
    partial void Insertpersona(persona instance);
    partial void Updatepersona(persona instance);
    partial void Deletepersona(persona instance);
    partial void Insertproducto(producto instance);
    partial void Updateproducto(producto instance);
    partial void Deleteproducto(producto instance);
    partial void Insertvendedor(vendedor instance);
    partial void Updatevendedor(vendedor instance);
    partial void Deletevendedor(vendedor instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::enciclopedia_canina_store.Properties.Settings.Default.Can_StoreConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<categoria> categorias
		{
			get
			{
				return this.GetTable<categoria>();
			}
		}
		
		public System.Data.Linq.Table<ciudad> ciudads
		{
			get
			{
				return this.GetTable<ciudad>();
			}
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Factura> Detalle_Facturas
		{
			get
			{
				return this.GetTable<Detalle_Factura>();
			}
		}
		
		public System.Data.Linq.Table<fabricante> fabricantes
		{
			get
			{
				return this.GetTable<fabricante>();
			}
		}
		
		public System.Data.Linq.Table<fac_ven_detalle> fac_ven_detalles
		{
			get
			{
				return this.GetTable<fac_ven_detalle>();
			}
		}
		
		public System.Data.Linq.Table<Factura_Reporte> Factura_Reportes
		{
			get
			{
				return this.GetTable<Factura_Reporte>();
			}
		}
		
		public System.Data.Linq.Table<factura_venta> factura_ventas
		{
			get
			{
				return this.GetTable<factura_venta>();
			}
		}
		
		public System.Data.Linq.Table<persona> personas
		{
			get
			{
				return this.GetTable<persona>();
			}
		}
		
		public System.Data.Linq.Table<persona_vendedor> persona_vendedors
		{
			get
			{
				return this.GetTable<persona_vendedor>();
			}
		}
		
		public System.Data.Linq.Table<producto> productos
		{
			get
			{
				return this.GetTable<producto>();
			}
		}
		
		public System.Data.Linq.Table<vendedor> vendedors
		{
			get
			{
				return this.GetTable<vendedor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categoria")]
	public partial class categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cat_codigo;
		
		private string _cat_nombre;
		
		private EntitySet<producto> _productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_codigoChanging(int value);
    partial void Oncat_codigoChanged();
    partial void Oncat_nombreChanging(string value);
    partial void Oncat_nombreChanged();
    #endregion
		
		public categoria()
		{
			this._productos = new EntitySet<producto>(new Action<producto>(this.attach_productos), new Action<producto>(this.detach_productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cat_codigo
		{
			get
			{
				return this._cat_codigo;
			}
			set
			{
				if ((this._cat_codigo != value))
				{
					this.Oncat_codigoChanging(value);
					this.SendPropertyChanging();
					this._cat_codigo = value;
					this.SendPropertyChanged("cat_codigo");
					this.Oncat_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_nombre", DbType="NVarChar(50)")]
		public string cat_nombre
		{
			get
			{
				return this._cat_nombre;
			}
			set
			{
				if ((this._cat_nombre != value))
				{
					this.Oncat_nombreChanging(value);
					this.SendPropertyChanging();
					this._cat_nombre = value;
					this.SendPropertyChanged("cat_nombre");
					this.Oncat_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_producto", Storage="_productos", ThisKey="cat_codigo", OtherKey="cat_codigo")]
		public EntitySet<producto> productos
		{
			get
			{
				return this._productos;
			}
			set
			{
				this._productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_productos(producto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = this;
		}
		
		private void detach_productos(producto entity)
		{
			this.SendPropertyChanging();
			entity.categoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ciudad")]
	public partial class ciudad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ciu_codigo;
		
		private string _ciu_nombre;
		
		private EntitySet<persona> _personas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onciu_codigoChanging(int value);
    partial void Onciu_codigoChanged();
    partial void Onciu_nombreChanging(string value);
    partial void Onciu_nombreChanged();
    #endregion
		
		public ciudad()
		{
			this._personas = new EntitySet<persona>(new Action<persona>(this.attach_personas), new Action<persona>(this.detach_personas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciu_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ciu_codigo
		{
			get
			{
				return this._ciu_codigo;
			}
			set
			{
				if ((this._ciu_codigo != value))
				{
					this.Onciu_codigoChanging(value);
					this.SendPropertyChanging();
					this._ciu_codigo = value;
					this.SendPropertyChanged("ciu_codigo");
					this.Onciu_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciu_nombre", DbType="NVarChar(50)")]
		public string ciu_nombre
		{
			get
			{
				return this._ciu_nombre;
			}
			set
			{
				if ((this._ciu_nombre != value))
				{
					this.Onciu_nombreChanging(value);
					this.SendPropertyChanging();
					this._ciu_nombre = value;
					this.SendPropertyChanged("ciu_nombre");
					this.Onciu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciudad_persona", Storage="_personas", ThisKey="ciu_codigo", OtherKey="ciu_codigo")]
		public EntitySet<persona> personas
		{
			get
			{
				return this._personas;
			}
			set
			{
				this._personas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_personas(persona entity)
		{
			this.SendPropertyChanging();
			entity.ciudad = this;
		}
		
		private void detach_personas(persona entity)
		{
			this.SendPropertyChanging();
			entity.ciudad = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cliente")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cli_codigo;
		
		private string _cli_tipo;
		
		private string _cli_saldo;
		
		private EntitySet<factura_venta> _factura_ventas;
		
		private EntityRef<persona> _persona;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncli_codigoChanging(int value);
    partial void Oncli_codigoChanged();
    partial void Oncli_tipoChanging(string value);
    partial void Oncli_tipoChanged();
    partial void Oncli_saldoChanging(string value);
    partial void Oncli_saldoChanged();
    #endregion
		
		public cliente()
		{
			this._factura_ventas = new EntitySet<factura_venta>(new Action<factura_venta>(this.attach_factura_ventas), new Action<factura_venta>(this.detach_factura_ventas));
			this._persona = default(EntityRef<persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cli_codigo
		{
			get
			{
				return this._cli_codigo;
			}
			set
			{
				if ((this._cli_codigo != value))
				{
					if (this._persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncli_codigoChanging(value);
					this.SendPropertyChanging();
					this._cli_codigo = value;
					this.SendPropertyChanged("cli_codigo");
					this.Oncli_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_tipo", DbType="NVarChar(50)")]
		public string cli_tipo
		{
			get
			{
				return this._cli_tipo;
			}
			set
			{
				if ((this._cli_tipo != value))
				{
					this.Oncli_tipoChanging(value);
					this.SendPropertyChanging();
					this._cli_tipo = value;
					this.SendPropertyChanged("cli_tipo");
					this.Oncli_tipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_saldo", DbType="NVarChar(50)")]
		public string cli_saldo
		{
			get
			{
				return this._cli_saldo;
			}
			set
			{
				if ((this._cli_saldo != value))
				{
					this.Oncli_saldoChanging(value);
					this.SendPropertyChanging();
					this._cli_saldo = value;
					this.SendPropertyChanged("cli_saldo");
					this.Oncli_saldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_factura_venta", Storage="_factura_ventas", ThisKey="cli_codigo", OtherKey="cli_codigo")]
		public EntitySet<factura_venta> factura_ventas
		{
			get
			{
				return this._factura_ventas;
			}
			set
			{
				this._factura_ventas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_cliente", Storage="_persona", ThisKey="cli_codigo", OtherKey="per_codigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public persona persona
		{
			get
			{
				return this._persona.Entity;
			}
			set
			{
				persona previousValue = this._persona.Entity;
				if (((previousValue != value) 
							|| (this._persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._persona.Entity = null;
						previousValue.cliente = null;
					}
					this._persona.Entity = value;
					if ((value != null))
					{
						value.cliente = this;
						this._cli_codigo = value.per_codigo;
					}
					else
					{
						this._cli_codigo = default(int);
					}
					this.SendPropertyChanged("persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_factura_ventas(factura_venta entity)
		{
			this.SendPropertyChanging();
			entity.cliente = this;
		}
		
		private void detach_factura_ventas(factura_venta entity)
		{
			this.SendPropertyChanging();
			entity.cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Factura")]
	public partial class Detalle_Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pro_codigo;
		
		private string _pro_nombre;
		
		private string _precio_unidad;
		
		private string _precio_total;
		
		private string _fac_numero;
		
		private string _cantidad;
		
		private int _fac_ven_detalle;
		
		private EntityRef<Factura_Reporte> _Factura_Reporte;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_codigoChanging(string value);
    partial void Onpro_codigoChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onprecio_unidadChanging(string value);
    partial void Onprecio_unidadChanged();
    partial void Onprecio_totalChanging(string value);
    partial void Onprecio_totalChanged();
    partial void Onfac_numeroChanging(string value);
    partial void Onfac_numeroChanged();
    partial void OncantidadChanging(string value);
    partial void OncantidadChanged();
    partial void Onfac_ven_detalleChanging(int value);
    partial void Onfac_ven_detalleChanged();
    #endregion
		
		public Detalle_Factura()
		{
			this._Factura_Reporte = default(EntityRef<Factura_Reporte>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="NVarChar(50)")]
		public string pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="NVarChar(50)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_unidad", DbType="NVarChar(50)")]
		public string precio_unidad
		{
			get
			{
				return this._precio_unidad;
			}
			set
			{
				if ((this._precio_unidad != value))
				{
					this.Onprecio_unidadChanging(value);
					this.SendPropertyChanging();
					this._precio_unidad = value;
					this.SendPropertyChanged("precio_unidad");
					this.Onprecio_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_total", DbType="NVarChar(50)")]
		public string precio_total
		{
			get
			{
				return this._precio_total;
			}
			set
			{
				if ((this._precio_total != value))
				{
					this.Onprecio_totalChanging(value);
					this.SendPropertyChanging();
					this._precio_total = value;
					this.SendPropertyChanged("precio_total");
					this.Onprecio_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_numero", DbType="NVarChar(50)")]
		public string fac_numero
		{
			get
			{
				return this._fac_numero;
			}
			set
			{
				if ((this._fac_numero != value))
				{
					if (this._Factura_Reporte.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfac_numeroChanging(value);
					this.SendPropertyChanging();
					this._fac_numero = value;
					this.SendPropertyChanged("fac_numero");
					this.Onfac_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="NVarChar(50)")]
		public string cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_ven_detalle", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fac_ven_detalle
		{
			get
			{
				return this._fac_ven_detalle;
			}
			set
			{
				if ((this._fac_ven_detalle != value))
				{
					this.Onfac_ven_detalleChanging(value);
					this.SendPropertyChanging();
					this._fac_ven_detalle = value;
					this.SendPropertyChanged("fac_ven_detalle");
					this.Onfac_ven_detalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Reporte_Detalle_Factura", Storage="_Factura_Reporte", ThisKey="fac_numero", OtherKey="fac_numero", IsForeignKey=true, DeleteRule="CASCADE")]
		public Factura_Reporte Factura_Reporte
		{
			get
			{
				return this._Factura_Reporte.Entity;
			}
			set
			{
				Factura_Reporte previousValue = this._Factura_Reporte.Entity;
				if (((previousValue != value) 
							|| (this._Factura_Reporte.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Factura_Reporte.Entity = null;
						previousValue.Detalle_Facturas.Remove(this);
					}
					this._Factura_Reporte.Entity = value;
					if ((value != null))
					{
						value.Detalle_Facturas.Add(this);
						this._fac_numero = value.fac_numero;
					}
					else
					{
						this._fac_numero = default(string);
					}
					this.SendPropertyChanged("Factura_Reporte");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fabricante")]
	public partial class fabricante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fab_codigo;
		
		private string _fab_nombre;
		
		private EntitySet<producto> _productos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfab_codigoChanging(int value);
    partial void Onfab_codigoChanged();
    partial void Onfab_nombreChanging(string value);
    partial void Onfab_nombreChanged();
    #endregion
		
		public fabricante()
		{
			this._productos = new EntitySet<producto>(new Action<producto>(this.attach_productos), new Action<producto>(this.detach_productos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fab_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fab_codigo
		{
			get
			{
				return this._fab_codigo;
			}
			set
			{
				if ((this._fab_codigo != value))
				{
					this.Onfab_codigoChanging(value);
					this.SendPropertyChanging();
					this._fab_codigo = value;
					this.SendPropertyChanged("fab_codigo");
					this.Onfab_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fab_nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string fab_nombre
		{
			get
			{
				return this._fab_nombre;
			}
			set
			{
				if ((this._fab_nombre != value))
				{
					this.Onfab_nombreChanging(value);
					this.SendPropertyChanging();
					this._fab_nombre = value;
					this.SendPropertyChanged("fab_nombre");
					this.Onfab_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fabricante_producto", Storage="_productos", ThisKey="fab_codigo", OtherKey="fab_codigo")]
		public EntitySet<producto> productos
		{
			get
			{
				return this._productos;
			}
			set
			{
				this._productos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_productos(producto entity)
		{
			this.SendPropertyChanging();
			entity.fabricante = this;
		}
		
		private void detach_productos(producto entity)
		{
			this.SendPropertyChanging();
			entity.fabricante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fac_ven_detalle")]
	public partial class fac_ven_detalle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fac_ven_detalle1;
		
		private int _fac_codigo;
		
		private int _pro_id;
		
		private System.Nullable<int> _fv_cantidad;
		
		private System.Nullable<decimal> _fv_puv;
		
		private System.Nullable<decimal> _fv_iva;
		
		private System.Nullable<decimal> _fv_descuento;
		
		private System.Nullable<bool> _fv_estado;
		
		private EntityRef<factura_venta> _factura_venta;
		
		private EntityRef<producto> _producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfac_ven_detalle1Changing(int value);
    partial void Onfac_ven_detalle1Changed();
    partial void Onfac_codigoChanging(int value);
    partial void Onfac_codigoChanged();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onfv_cantidadChanging(System.Nullable<int> value);
    partial void Onfv_cantidadChanged();
    partial void Onfv_puvChanging(System.Nullable<decimal> value);
    partial void Onfv_puvChanged();
    partial void Onfv_ivaChanging(System.Nullable<decimal> value);
    partial void Onfv_ivaChanged();
    partial void Onfv_descuentoChanging(System.Nullable<decimal> value);
    partial void Onfv_descuentoChanged();
    partial void Onfv_estadoChanging(System.Nullable<bool> value);
    partial void Onfv_estadoChanged();
    #endregion
		
		public fac_ven_detalle()
		{
			this._factura_venta = default(EntityRef<factura_venta>);
			this._producto = default(EntityRef<producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="fac_ven_detalle", Storage="_fac_ven_detalle1", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fac_ven_detalle1
		{
			get
			{
				return this._fac_ven_detalle1;
			}
			set
			{
				if ((this._fac_ven_detalle1 != value))
				{
					this.Onfac_ven_detalle1Changing(value);
					this.SendPropertyChanging();
					this._fac_ven_detalle1 = value;
					this.SendPropertyChanged("fac_ven_detalle1");
					this.Onfac_ven_detalle1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_codigo", DbType="Int NOT NULL")]
		public int fac_codigo
		{
			get
			{
				return this._fac_codigo;
			}
			set
			{
				if ((this._fac_codigo != value))
				{
					if (this._factura_venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfac_codigoChanging(value);
					this.SendPropertyChanging();
					this._fac_codigo = value;
					this.SendPropertyChanged("fac_codigo");
					this.Onfac_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL")]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fv_cantidad", DbType="Int")]
		public System.Nullable<int> fv_cantidad
		{
			get
			{
				return this._fv_cantidad;
			}
			set
			{
				if ((this._fv_cantidad != value))
				{
					this.Onfv_cantidadChanging(value);
					this.SendPropertyChanging();
					this._fv_cantidad = value;
					this.SendPropertyChanged("fv_cantidad");
					this.Onfv_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fv_puv", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fv_puv
		{
			get
			{
				return this._fv_puv;
			}
			set
			{
				if ((this._fv_puv != value))
				{
					this.Onfv_puvChanging(value);
					this.SendPropertyChanging();
					this._fv_puv = value;
					this.SendPropertyChanged("fv_puv");
					this.Onfv_puvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fv_iva", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fv_iva
		{
			get
			{
				return this._fv_iva;
			}
			set
			{
				if ((this._fv_iva != value))
				{
					this.Onfv_ivaChanging(value);
					this.SendPropertyChanging();
					this._fv_iva = value;
					this.SendPropertyChanged("fv_iva");
					this.Onfv_ivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fv_descuento", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fv_descuento
		{
			get
			{
				return this._fv_descuento;
			}
			set
			{
				if ((this._fv_descuento != value))
				{
					this.Onfv_descuentoChanging(value);
					this.SendPropertyChanging();
					this._fv_descuento = value;
					this.SendPropertyChanged("fv_descuento");
					this.Onfv_descuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fv_estado", DbType="Bit")]
		public System.Nullable<bool> fv_estado
		{
			get
			{
				return this._fv_estado;
			}
			set
			{
				if ((this._fv_estado != value))
				{
					this.Onfv_estadoChanging(value);
					this.SendPropertyChanging();
					this._fv_estado = value;
					this.SendPropertyChanged("fv_estado");
					this.Onfv_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="factura_venta_fac_ven_detalle", Storage="_factura_venta", ThisKey="fac_codigo", OtherKey="fac_codigo", IsForeignKey=true)]
		public factura_venta factura_venta
		{
			get
			{
				return this._factura_venta.Entity;
			}
			set
			{
				factura_venta previousValue = this._factura_venta.Entity;
				if (((previousValue != value) 
							|| (this._factura_venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._factura_venta.Entity = null;
						previousValue.fac_ven_detalles.Remove(this);
					}
					this._factura_venta.Entity = value;
					if ((value != null))
					{
						value.fac_ven_detalles.Add(this);
						this._fac_codigo = value.fac_codigo;
					}
					else
					{
						this._fac_codigo = default(int);
					}
					this.SendPropertyChanged("factura_venta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_fac_ven_detalle", Storage="_producto", ThisKey="pro_id", OtherKey="pro_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.fac_ven_detalles.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.fac_ven_detalles.Add(this);
						this._pro_id = value.pro_id;
					}
					else
					{
						this._pro_id = default(int);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Factura_Reporte")]
	public partial class Factura_Reporte : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _fac_numero;
		
		private string _per_nombre;
		
		private string _per_apellido;
		
		private string _per_direccion;
		
		private string _per_telefono;
		
		private string _per_ruc;
		
		private string _total_pagar;
		
		private EntitySet<Detalle_Factura> _Detalle_Facturas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfac_numeroChanging(string value);
    partial void Onfac_numeroChanged();
    partial void Onper_nombreChanging(string value);
    partial void Onper_nombreChanged();
    partial void Onper_apellidoChanging(string value);
    partial void Onper_apellidoChanged();
    partial void Onper_direccionChanging(string value);
    partial void Onper_direccionChanged();
    partial void Onper_telefonoChanging(string value);
    partial void Onper_telefonoChanged();
    partial void Onper_rucChanging(string value);
    partial void Onper_rucChanged();
    partial void Ontotal_pagarChanging(string value);
    partial void Ontotal_pagarChanged();
    #endregion
		
		public Factura_Reporte()
		{
			this._Detalle_Facturas = new EntitySet<Detalle_Factura>(new Action<Detalle_Factura>(this.attach_Detalle_Facturas), new Action<Detalle_Factura>(this.detach_Detalle_Facturas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_numero", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string fac_numero
		{
			get
			{
				return this._fac_numero;
			}
			set
			{
				if ((this._fac_numero != value))
				{
					this.Onfac_numeroChanging(value);
					this.SendPropertyChanging();
					this._fac_numero = value;
					this.SendPropertyChanged("fac_numero");
					this.Onfac_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_nombre", DbType="NVarChar(50)")]
		public string per_nombre
		{
			get
			{
				return this._per_nombre;
			}
			set
			{
				if ((this._per_nombre != value))
				{
					this.Onper_nombreChanging(value);
					this.SendPropertyChanging();
					this._per_nombre = value;
					this.SendPropertyChanged("per_nombre");
					this.Onper_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_apellido", DbType="NVarChar(50)")]
		public string per_apellido
		{
			get
			{
				return this._per_apellido;
			}
			set
			{
				if ((this._per_apellido != value))
				{
					this.Onper_apellidoChanging(value);
					this.SendPropertyChanging();
					this._per_apellido = value;
					this.SendPropertyChanged("per_apellido");
					this.Onper_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_direccion", DbType="NVarChar(50)")]
		public string per_direccion
		{
			get
			{
				return this._per_direccion;
			}
			set
			{
				if ((this._per_direccion != value))
				{
					this.Onper_direccionChanging(value);
					this.SendPropertyChanging();
					this._per_direccion = value;
					this.SendPropertyChanged("per_direccion");
					this.Onper_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_telefono", DbType="NVarChar(50)")]
		public string per_telefono
		{
			get
			{
				return this._per_telefono;
			}
			set
			{
				if ((this._per_telefono != value))
				{
					this.Onper_telefonoChanging(value);
					this.SendPropertyChanging();
					this._per_telefono = value;
					this.SendPropertyChanged("per_telefono");
					this.Onper_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ruc", DbType="NVarChar(50)")]
		public string per_ruc
		{
			get
			{
				return this._per_ruc;
			}
			set
			{
				if ((this._per_ruc != value))
				{
					this.Onper_rucChanging(value);
					this.SendPropertyChanging();
					this._per_ruc = value;
					this.SendPropertyChanged("per_ruc");
					this.Onper_rucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_pagar", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string total_pagar
		{
			get
			{
				return this._total_pagar;
			}
			set
			{
				if ((this._total_pagar != value))
				{
					this.Ontotal_pagarChanging(value);
					this.SendPropertyChanging();
					this._total_pagar = value;
					this.SendPropertyChanged("total_pagar");
					this.Ontotal_pagarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Factura_Reporte_Detalle_Factura", Storage="_Detalle_Facturas", ThisKey="fac_numero", OtherKey="fac_numero")]
		public EntitySet<Detalle_Factura> Detalle_Facturas
		{
			get
			{
				return this._Detalle_Facturas;
			}
			set
			{
				this._Detalle_Facturas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Facturas(Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Factura_Reporte = this;
		}
		
		private void detach_Detalle_Facturas(Detalle_Factura entity)
		{
			this.SendPropertyChanging();
			entity.Factura_Reporte = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.factura_venta")]
	public partial class factura_venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fac_codigo;
		
		private string _fac_numero;
		
		private System.Nullable<System.DateTime> _fac_fecha;
		
		private System.Nullable<int> _cli_codigo;
		
		private System.Nullable<int> _ven_codigo;
		
		private System.Nullable<decimal> _fac_subtotal;
		
		private System.Nullable<decimal> _fac_subcero;
		
		private System.Nullable<decimal> _fac_subiva;
		
		private System.Nullable<decimal> _fac_total;
		
		private System.Nullable<decimal> _fac_descuento;
		
		private System.Nullable<bool> _fac_estado;
		
		private EntitySet<fac_ven_detalle> _fac_ven_detalles;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<vendedor> _vendedor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfac_codigoChanging(int value);
    partial void Onfac_codigoChanged();
    partial void Onfac_numeroChanging(string value);
    partial void Onfac_numeroChanged();
    partial void Onfac_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onfac_fechaChanged();
    partial void Oncli_codigoChanging(System.Nullable<int> value);
    partial void Oncli_codigoChanged();
    partial void Onven_codigoChanging(System.Nullable<int> value);
    partial void Onven_codigoChanged();
    partial void Onfac_subtotalChanging(System.Nullable<decimal> value);
    partial void Onfac_subtotalChanged();
    partial void Onfac_subceroChanging(System.Nullable<decimal> value);
    partial void Onfac_subceroChanged();
    partial void Onfac_subivaChanging(System.Nullable<decimal> value);
    partial void Onfac_subivaChanged();
    partial void Onfac_totalChanging(System.Nullable<decimal> value);
    partial void Onfac_totalChanged();
    partial void Onfac_descuentoChanging(System.Nullable<decimal> value);
    partial void Onfac_descuentoChanged();
    partial void Onfac_estadoChanging(System.Nullable<bool> value);
    partial void Onfac_estadoChanged();
    #endregion
		
		public factura_venta()
		{
			this._fac_ven_detalles = new EntitySet<fac_ven_detalle>(new Action<fac_ven_detalle>(this.attach_fac_ven_detalles), new Action<fac_ven_detalle>(this.detach_fac_ven_detalles));
			this._cliente = default(EntityRef<cliente>);
			this._vendedor = default(EntityRef<vendedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int fac_codigo
		{
			get
			{
				return this._fac_codigo;
			}
			set
			{
				if ((this._fac_codigo != value))
				{
					this.Onfac_codigoChanging(value);
					this.SendPropertyChanging();
					this._fac_codigo = value;
					this.SendPropertyChanged("fac_codigo");
					this.Onfac_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_numero", DbType="NVarChar(10)")]
		public string fac_numero
		{
			get
			{
				return this._fac_numero;
			}
			set
			{
				if ((this._fac_numero != value))
				{
					this.Onfac_numeroChanging(value);
					this.SendPropertyChanging();
					this._fac_numero = value;
					this.SendPropertyChanged("fac_numero");
					this.Onfac_numeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fac_fecha
		{
			get
			{
				return this._fac_fecha;
			}
			set
			{
				if ((this._fac_fecha != value))
				{
					this.Onfac_fechaChanging(value);
					this.SendPropertyChanging();
					this._fac_fecha = value;
					this.SendPropertyChanged("fac_fecha");
					this.Onfac_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cli_codigo", DbType="Int")]
		public System.Nullable<int> cli_codigo
		{
			get
			{
				return this._cli_codigo;
			}
			set
			{
				if ((this._cli_codigo != value))
				{
					if (this._cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncli_codigoChanging(value);
					this.SendPropertyChanging();
					this._cli_codigo = value;
					this.SendPropertyChanged("cli_codigo");
					this.Oncli_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_codigo", DbType="Int")]
		public System.Nullable<int> ven_codigo
		{
			get
			{
				return this._ven_codigo;
			}
			set
			{
				if ((this._ven_codigo != value))
				{
					if (this._vendedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onven_codigoChanging(value);
					this.SendPropertyChanging();
					this._ven_codigo = value;
					this.SendPropertyChanged("ven_codigo");
					this.Onven_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_subtotal", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fac_subtotal
		{
			get
			{
				return this._fac_subtotal;
			}
			set
			{
				if ((this._fac_subtotal != value))
				{
					this.Onfac_subtotalChanging(value);
					this.SendPropertyChanging();
					this._fac_subtotal = value;
					this.SendPropertyChanged("fac_subtotal");
					this.Onfac_subtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_subcero", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fac_subcero
		{
			get
			{
				return this._fac_subcero;
			}
			set
			{
				if ((this._fac_subcero != value))
				{
					this.Onfac_subceroChanging(value);
					this.SendPropertyChanging();
					this._fac_subcero = value;
					this.SendPropertyChanged("fac_subcero");
					this.Onfac_subceroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_subiva", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fac_subiva
		{
			get
			{
				return this._fac_subiva;
			}
			set
			{
				if ((this._fac_subiva != value))
				{
					this.Onfac_subivaChanging(value);
					this.SendPropertyChanging();
					this._fac_subiva = value;
					this.SendPropertyChanged("fac_subiva");
					this.Onfac_subivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fac_total
		{
			get
			{
				return this._fac_total;
			}
			set
			{
				if ((this._fac_total != value))
				{
					this.Onfac_totalChanging(value);
					this.SendPropertyChanging();
					this._fac_total = value;
					this.SendPropertyChanged("fac_total");
					this.Onfac_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_descuento", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> fac_descuento
		{
			get
			{
				return this._fac_descuento;
			}
			set
			{
				if ((this._fac_descuento != value))
				{
					this.Onfac_descuentoChanging(value);
					this.SendPropertyChanging();
					this._fac_descuento = value;
					this.SendPropertyChanged("fac_descuento");
					this.Onfac_descuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_estado", DbType="Bit")]
		public System.Nullable<bool> fac_estado
		{
			get
			{
				return this._fac_estado;
			}
			set
			{
				if ((this._fac_estado != value))
				{
					this.Onfac_estadoChanging(value);
					this.SendPropertyChanging();
					this._fac_estado = value;
					this.SendPropertyChanged("fac_estado");
					this.Onfac_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="factura_venta_fac_ven_detalle", Storage="_fac_ven_detalles", ThisKey="fac_codigo", OtherKey="fac_codigo")]
		public EntitySet<fac_ven_detalle> fac_ven_detalles
		{
			get
			{
				return this._fac_ven_detalles;
			}
			set
			{
				this._fac_ven_detalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_factura_venta", Storage="_cliente", ThisKey="cli_codigo", OtherKey="cli_codigo", IsForeignKey=true)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.factura_ventas.Remove(this);
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.factura_ventas.Add(this);
						this._cli_codigo = value.cli_codigo;
					}
					else
					{
						this._cli_codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vendedor_factura_venta", Storage="_vendedor", ThisKey="ven_codigo", OtherKey="ven_codigo", IsForeignKey=true, DeleteRule="CASCADE")]
		public vendedor vendedor
		{
			get
			{
				return this._vendedor.Entity;
			}
			set
			{
				vendedor previousValue = this._vendedor.Entity;
				if (((previousValue != value) 
							|| (this._vendedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._vendedor.Entity = null;
						previousValue.factura_ventas.Remove(this);
					}
					this._vendedor.Entity = value;
					if ((value != null))
					{
						value.factura_ventas.Add(this);
						this._ven_codigo = value.ven_codigo;
					}
					else
					{
						this._ven_codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("vendedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_fac_ven_detalles(fac_ven_detalle entity)
		{
			this.SendPropertyChanging();
			entity.factura_venta = this;
		}
		
		private void detach_fac_ven_detalles(fac_ven_detalle entity)
		{
			this.SendPropertyChanging();
			entity.factura_venta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.persona")]
	public partial class persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _per_codigo;
		
		private string _per_nombre;
		
		private string _per_apellido;
		
		private string _per_ruc;
		
		private string _per_direccion;
		
		private string _per_telefono;
		
		private System.Nullable<int> _ciu_codigo;
		
		private string _per_email;
		
		private EntityRef<cliente> _cliente;
		
		private EntityRef<vendedor> _vendedor;
		
		private EntityRef<ciudad> _ciudad;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onper_codigoChanging(int value);
    partial void Onper_codigoChanged();
    partial void Onper_nombreChanging(string value);
    partial void Onper_nombreChanged();
    partial void Onper_apellidoChanging(string value);
    partial void Onper_apellidoChanged();
    partial void Onper_rucChanging(string value);
    partial void Onper_rucChanged();
    partial void Onper_direccionChanging(string value);
    partial void Onper_direccionChanged();
    partial void Onper_telefonoChanging(string value);
    partial void Onper_telefonoChanged();
    partial void Onciu_codigoChanging(System.Nullable<int> value);
    partial void Onciu_codigoChanged();
    partial void Onper_emailChanging(string value);
    partial void Onper_emailChanged();
    #endregion
		
		public persona()
		{
			this._cliente = default(EntityRef<cliente>);
			this._vendedor = default(EntityRef<vendedor>);
			this._ciudad = default(EntityRef<ciudad>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int per_codigo
		{
			get
			{
				return this._per_codigo;
			}
			set
			{
				if ((this._per_codigo != value))
				{
					this.Onper_codigoChanging(value);
					this.SendPropertyChanging();
					this._per_codigo = value;
					this.SendPropertyChanged("per_codigo");
					this.Onper_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_nombre", DbType="NVarChar(50)")]
		public string per_nombre
		{
			get
			{
				return this._per_nombre;
			}
			set
			{
				if ((this._per_nombre != value))
				{
					this.Onper_nombreChanging(value);
					this.SendPropertyChanging();
					this._per_nombre = value;
					this.SendPropertyChanged("per_nombre");
					this.Onper_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_apellido", DbType="NVarChar(50)")]
		public string per_apellido
		{
			get
			{
				return this._per_apellido;
			}
			set
			{
				if ((this._per_apellido != value))
				{
					this.Onper_apellidoChanging(value);
					this.SendPropertyChanging();
					this._per_apellido = value;
					this.SendPropertyChanged("per_apellido");
					this.Onper_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ruc", DbType="NVarChar(50)")]
		public string per_ruc
		{
			get
			{
				return this._per_ruc;
			}
			set
			{
				if ((this._per_ruc != value))
				{
					this.Onper_rucChanging(value);
					this.SendPropertyChanging();
					this._per_ruc = value;
					this.SendPropertyChanged("per_ruc");
					this.Onper_rucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_direccion", DbType="NVarChar(50)")]
		public string per_direccion
		{
			get
			{
				return this._per_direccion;
			}
			set
			{
				if ((this._per_direccion != value))
				{
					this.Onper_direccionChanging(value);
					this.SendPropertyChanging();
					this._per_direccion = value;
					this.SendPropertyChanged("per_direccion");
					this.Onper_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_telefono", DbType="NVarChar(50)")]
		public string per_telefono
		{
			get
			{
				return this._per_telefono;
			}
			set
			{
				if ((this._per_telefono != value))
				{
					this.Onper_telefonoChanging(value);
					this.SendPropertyChanging();
					this._per_telefono = value;
					this.SendPropertyChanged("per_telefono");
					this.Onper_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciu_codigo", DbType="Int")]
		public System.Nullable<int> ciu_codigo
		{
			get
			{
				return this._ciu_codigo;
			}
			set
			{
				if ((this._ciu_codigo != value))
				{
					if (this._ciudad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onciu_codigoChanging(value);
					this.SendPropertyChanging();
					this._ciu_codigo = value;
					this.SendPropertyChanged("ciu_codigo");
					this.Onciu_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_email", DbType="NVarChar(50)")]
		public string per_email
		{
			get
			{
				return this._per_email;
			}
			set
			{
				if ((this._per_email != value))
				{
					this.Onper_emailChanging(value);
					this.SendPropertyChanging();
					this._per_email = value;
					this.SendPropertyChanged("per_email");
					this.Onper_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_cliente", Storage="_cliente", ThisKey="per_codigo", OtherKey="cli_codigo", IsUnique=true, IsForeignKey=false)]
		public cliente cliente
		{
			get
			{
				return this._cliente.Entity;
			}
			set
			{
				cliente previousValue = this._cliente.Entity;
				if (((previousValue != value) 
							|| (this._cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente.Entity = null;
						previousValue.persona = null;
					}
					this._cliente.Entity = value;
					if ((value != null))
					{
						value.persona = this;
					}
					this.SendPropertyChanged("cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_vendedor", Storage="_vendedor", ThisKey="per_codigo", OtherKey="ven_codigo", IsUnique=true, IsForeignKey=false)]
		public vendedor vendedor
		{
			get
			{
				return this._vendedor.Entity;
			}
			set
			{
				vendedor previousValue = this._vendedor.Entity;
				if (((previousValue != value) 
							|| (this._vendedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._vendedor.Entity = null;
						previousValue.persona = null;
					}
					this._vendedor.Entity = value;
					if ((value != null))
					{
						value.persona = this;
					}
					this.SendPropertyChanged("vendedor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ciudad_persona", Storage="_ciudad", ThisKey="ciu_codigo", OtherKey="ciu_codigo", IsForeignKey=true, DeleteRule="CASCADE")]
		public ciudad ciudad
		{
			get
			{
				return this._ciudad.Entity;
			}
			set
			{
				ciudad previousValue = this._ciudad.Entity;
				if (((previousValue != value) 
							|| (this._ciudad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ciudad.Entity = null;
						previousValue.personas.Remove(this);
					}
					this._ciudad.Entity = value;
					if ((value != null))
					{
						value.personas.Add(this);
						this._ciu_codigo = value.ciu_codigo;
					}
					else
					{
						this._ciu_codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("ciudad");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.persona_vendedor")]
	public partial class persona_vendedor
	{
		
		private string _per_nombre;
		
		private string _per_ruc;
		
		private string _per_direccion;
		
		private string _per_telefono;
		
		private string _per_email;
		
		private System.Nullable<decimal> _ven_sueldo;
		
		private string _ven_user;
		
		public persona_vendedor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_nombre", DbType="NVarChar(50)")]
		public string per_nombre
		{
			get
			{
				return this._per_nombre;
			}
			set
			{
				if ((this._per_nombre != value))
				{
					this._per_nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_ruc", DbType="NVarChar(50)")]
		public string per_ruc
		{
			get
			{
				return this._per_ruc;
			}
			set
			{
				if ((this._per_ruc != value))
				{
					this._per_ruc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_direccion", DbType="NVarChar(50)")]
		public string per_direccion
		{
			get
			{
				return this._per_direccion;
			}
			set
			{
				if ((this._per_direccion != value))
				{
					this._per_direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_telefono", DbType="NVarChar(50)")]
		public string per_telefono
		{
			get
			{
				return this._per_telefono;
			}
			set
			{
				if ((this._per_telefono != value))
				{
					this._per_telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_email", DbType="NVarChar(50)")]
		public string per_email
		{
			get
			{
				return this._per_email;
			}
			set
			{
				if ((this._per_email != value))
				{
					this._per_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_sueldo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ven_sueldo
		{
			get
			{
				return this._ven_sueldo;
			}
			set
			{
				if ((this._ven_sueldo != value))
				{
					this._ven_sueldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_user", DbType="NVarChar(50)")]
		public string ven_user
		{
			get
			{
				return this._ven_user;
			}
			set
			{
				if ((this._ven_user != value))
				{
					this._ven_user = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producto")]
	public partial class producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _pro_nombre;
		
		private string _pro_descripcion;
		
		private System.Nullable<int> _pro_cantidad;
		
		private System.Nullable<decimal> _pro_precio_compra;
		
		private System.Nullable<decimal> _pro_precio_venta;
		
		private System.Nullable<int> _cat_codigo;
		
		private System.Nullable<int> _fab_codigo;
		
		private string _pro_codigo;
		
		private System.Nullable<bool> _pro_iva;
		
		private System.Nullable<bool> _pro_estado;
		
		private System.Nullable<decimal> _pro_desc_porcen;
		
		private EntitySet<fac_ven_detalle> _fac_ven_detalles;
		
		private EntityRef<categoria> _categoria;
		
		private EntityRef<fabricante> _fabricante;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void Onpro_nombreChanging(string value);
    partial void Onpro_nombreChanged();
    partial void Onpro_descripcionChanging(string value);
    partial void Onpro_descripcionChanged();
    partial void Onpro_cantidadChanging(System.Nullable<int> value);
    partial void Onpro_cantidadChanged();
    partial void Onpro_precio_compraChanging(System.Nullable<decimal> value);
    partial void Onpro_precio_compraChanged();
    partial void Onpro_precio_ventaChanging(System.Nullable<decimal> value);
    partial void Onpro_precio_ventaChanged();
    partial void Oncat_codigoChanging(System.Nullable<int> value);
    partial void Oncat_codigoChanged();
    partial void Onfab_codigoChanging(System.Nullable<int> value);
    partial void Onfab_codigoChanged();
    partial void Onpro_codigoChanging(string value);
    partial void Onpro_codigoChanged();
    partial void Onpro_ivaChanging(System.Nullable<bool> value);
    partial void Onpro_ivaChanged();
    partial void Onpro_estadoChanging(System.Nullable<bool> value);
    partial void Onpro_estadoChanged();
    partial void Onpro_desc_porcenChanging(System.Nullable<decimal> value);
    partial void Onpro_desc_porcenChanged();
    #endregion
		
		public producto()
		{
			this._fac_ven_detalles = new EntitySet<fac_ven_detalle>(new Action<fac_ven_detalle>(this.attach_fac_ven_detalles), new Action<fac_ven_detalle>(this.detach_fac_ven_detalles));
			this._categoria = default(EntityRef<categoria>);
			this._fabricante = default(EntityRef<fabricante>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_nombre", DbType="NVarChar(50)")]
		public string pro_nombre
		{
			get
			{
				return this._pro_nombre;
			}
			set
			{
				if ((this._pro_nombre != value))
				{
					this.Onpro_nombreChanging(value);
					this.SendPropertyChanging();
					this._pro_nombre = value;
					this.SendPropertyChanged("pro_nombre");
					this.Onpro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_descripcion", DbType="NVarChar(50)")]
		public string pro_descripcion
		{
			get
			{
				return this._pro_descripcion;
			}
			set
			{
				if ((this._pro_descripcion != value))
				{
					this.Onpro_descripcionChanging(value);
					this.SendPropertyChanging();
					this._pro_descripcion = value;
					this.SendPropertyChanged("pro_descripcion");
					this.Onpro_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_cantidad", DbType="Int")]
		public System.Nullable<int> pro_cantidad
		{
			get
			{
				return this._pro_cantidad;
			}
			set
			{
				if ((this._pro_cantidad != value))
				{
					this.Onpro_cantidadChanging(value);
					this.SendPropertyChanging();
					this._pro_cantidad = value;
					this.SendPropertyChanged("pro_cantidad");
					this.Onpro_cantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio_compra", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_precio_compra
		{
			get
			{
				return this._pro_precio_compra;
			}
			set
			{
				if ((this._pro_precio_compra != value))
				{
					this.Onpro_precio_compraChanging(value);
					this.SendPropertyChanging();
					this._pro_precio_compra = value;
					this.SendPropertyChanged("pro_precio_compra");
					this.Onpro_precio_compraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_precio_venta", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_precio_venta
		{
			get
			{
				return this._pro_precio_venta;
			}
			set
			{
				if ((this._pro_precio_venta != value))
				{
					this.Onpro_precio_ventaChanging(value);
					this.SendPropertyChanging();
					this._pro_precio_venta = value;
					this.SendPropertyChanged("pro_precio_venta");
					this.Onpro_precio_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_codigo", DbType="Int")]
		public System.Nullable<int> cat_codigo
		{
			get
			{
				return this._cat_codigo;
			}
			set
			{
				if ((this._cat_codigo != value))
				{
					if (this._categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncat_codigoChanging(value);
					this.SendPropertyChanging();
					this._cat_codigo = value;
					this.SendPropertyChanged("cat_codigo");
					this.Oncat_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fab_codigo", DbType="Int")]
		public System.Nullable<int> fab_codigo
		{
			get
			{
				return this._fab_codigo;
			}
			set
			{
				if ((this._fab_codigo != value))
				{
					if (this._fabricante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfab_codigoChanging(value);
					this.SendPropertyChanging();
					this._fab_codigo = value;
					this.SendPropertyChanged("fab_codigo");
					this.Onfab_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_codigo", DbType="NVarChar(50)")]
		public string pro_codigo
		{
			get
			{
				return this._pro_codigo;
			}
			set
			{
				if ((this._pro_codigo != value))
				{
					this.Onpro_codigoChanging(value);
					this.SendPropertyChanging();
					this._pro_codigo = value;
					this.SendPropertyChanged("pro_codigo");
					this.Onpro_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_iva", DbType="Bit")]
		public System.Nullable<bool> pro_iva
		{
			get
			{
				return this._pro_iva;
			}
			set
			{
				if ((this._pro_iva != value))
				{
					this.Onpro_ivaChanging(value);
					this.SendPropertyChanging();
					this._pro_iva = value;
					this.SendPropertyChanged("pro_iva");
					this.Onpro_ivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_estado", DbType="Bit")]
		public System.Nullable<bool> pro_estado
		{
			get
			{
				return this._pro_estado;
			}
			set
			{
				if ((this._pro_estado != value))
				{
					this.Onpro_estadoChanging(value);
					this.SendPropertyChanging();
					this._pro_estado = value;
					this.SendPropertyChanged("pro_estado");
					this.Onpro_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_desc_porcen", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> pro_desc_porcen
		{
			get
			{
				return this._pro_desc_porcen;
			}
			set
			{
				if ((this._pro_desc_porcen != value))
				{
					this.Onpro_desc_porcenChanging(value);
					this.SendPropertyChanging();
					this._pro_desc_porcen = value;
					this.SendPropertyChanged("pro_desc_porcen");
					this.Onpro_desc_porcenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_fac_ven_detalle", Storage="_fac_ven_detalles", ThisKey="pro_id", OtherKey="pro_id")]
		public EntitySet<fac_ven_detalle> fac_ven_detalles
		{
			get
			{
				return this._fac_ven_detalles;
			}
			set
			{
				this._fac_ven_detalles.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="categoria_producto", Storage="_categoria", ThisKey="cat_codigo", OtherKey="cat_codigo", IsForeignKey=true)]
		public categoria categoria
		{
			get
			{
				return this._categoria.Entity;
			}
			set
			{
				categoria previousValue = this._categoria.Entity;
				if (((previousValue != value) 
							|| (this._categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._categoria.Entity = null;
						previousValue.productos.Remove(this);
					}
					this._categoria.Entity = value;
					if ((value != null))
					{
						value.productos.Add(this);
						this._cat_codigo = value.cat_codigo;
					}
					else
					{
						this._cat_codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("categoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="fabricante_producto", Storage="_fabricante", ThisKey="fab_codigo", OtherKey="fab_codigo", IsForeignKey=true, DeleteRule="CASCADE")]
		public fabricante fabricante
		{
			get
			{
				return this._fabricante.Entity;
			}
			set
			{
				fabricante previousValue = this._fabricante.Entity;
				if (((previousValue != value) 
							|| (this._fabricante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._fabricante.Entity = null;
						previousValue.productos.Remove(this);
					}
					this._fabricante.Entity = value;
					if ((value != null))
					{
						value.productos.Add(this);
						this._fab_codigo = value.fab_codigo;
					}
					else
					{
						this._fab_codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("fabricante");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_fac_ven_detalles(fac_ven_detalle entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_fac_ven_detalles(fac_ven_detalle entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vendedor")]
	public partial class vendedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ven_codigo;
		
		private System.Nullable<decimal> _ven_sueldo;
		
		private System.DateTime _ven_fecha_ingreso;
		
		private bool _ven_estado;
		
		private string _ven_user;
		
		private string _ven_password;
		
		private EntitySet<factura_venta> _factura_ventas;
		
		private EntityRef<persona> _persona;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onven_codigoChanging(int value);
    partial void Onven_codigoChanged();
    partial void Onven_sueldoChanging(System.Nullable<decimal> value);
    partial void Onven_sueldoChanged();
    partial void Onven_fecha_ingresoChanging(System.DateTime value);
    partial void Onven_fecha_ingresoChanged();
    partial void Onven_estadoChanging(bool value);
    partial void Onven_estadoChanged();
    partial void Onven_userChanging(string value);
    partial void Onven_userChanged();
    partial void Onven_passwordChanging(string value);
    partial void Onven_passwordChanged();
    #endregion
		
		public vendedor()
		{
			this._factura_ventas = new EntitySet<factura_venta>(new Action<factura_venta>(this.attach_factura_ventas), new Action<factura_venta>(this.detach_factura_ventas));
			this._persona = default(EntityRef<persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_codigo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ven_codigo
		{
			get
			{
				return this._ven_codigo;
			}
			set
			{
				if ((this._ven_codigo != value))
				{
					if (this._persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onven_codigoChanging(value);
					this.SendPropertyChanging();
					this._ven_codigo = value;
					this.SendPropertyChanged("ven_codigo");
					this.Onven_codigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_sueldo", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ven_sueldo
		{
			get
			{
				return this._ven_sueldo;
			}
			set
			{
				if ((this._ven_sueldo != value))
				{
					this.Onven_sueldoChanging(value);
					this.SendPropertyChanging();
					this._ven_sueldo = value;
					this.SendPropertyChanged("ven_sueldo");
					this.Onven_sueldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_fecha_ingreso", DbType="Date NOT NULL")]
		public System.DateTime ven_fecha_ingreso
		{
			get
			{
				return this._ven_fecha_ingreso;
			}
			set
			{
				if ((this._ven_fecha_ingreso != value))
				{
					this.Onven_fecha_ingresoChanging(value);
					this.SendPropertyChanging();
					this._ven_fecha_ingreso = value;
					this.SendPropertyChanged("ven_fecha_ingreso");
					this.Onven_fecha_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_estado", DbType="Bit NOT NULL")]
		public bool ven_estado
		{
			get
			{
				return this._ven_estado;
			}
			set
			{
				if ((this._ven_estado != value))
				{
					this.Onven_estadoChanging(value);
					this.SendPropertyChanging();
					this._ven_estado = value;
					this.SendPropertyChanged("ven_estado");
					this.Onven_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_user", DbType="NVarChar(50)")]
		public string ven_user
		{
			get
			{
				return this._ven_user;
			}
			set
			{
				if ((this._ven_user != value))
				{
					this.Onven_userChanging(value);
					this.SendPropertyChanging();
					this._ven_user = value;
					this.SendPropertyChanged("ven_user");
					this.Onven_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ven_password", DbType="NVarChar(50)")]
		public string ven_password
		{
			get
			{
				return this._ven_password;
			}
			set
			{
				if ((this._ven_password != value))
				{
					this.Onven_passwordChanging(value);
					this.SendPropertyChanging();
					this._ven_password = value;
					this.SendPropertyChanged("ven_password");
					this.Onven_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vendedor_factura_venta", Storage="_factura_ventas", ThisKey="ven_codigo", OtherKey="ven_codigo")]
		public EntitySet<factura_venta> factura_ventas
		{
			get
			{
				return this._factura_ventas;
			}
			set
			{
				this._factura_ventas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="persona_vendedor", Storage="_persona", ThisKey="ven_codigo", OtherKey="per_codigo", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public persona persona
		{
			get
			{
				return this._persona.Entity;
			}
			set
			{
				persona previousValue = this._persona.Entity;
				if (((previousValue != value) 
							|| (this._persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._persona.Entity = null;
						previousValue.vendedor = null;
					}
					this._persona.Entity = value;
					if ((value != null))
					{
						value.vendedor = this;
						this._ven_codigo = value.per_codigo;
					}
					else
					{
						this._ven_codigo = default(int);
					}
					this.SendPropertyChanged("persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_factura_ventas(factura_venta entity)
		{
			this.SendPropertyChanging();
			entity.vendedor = this;
		}
		
		private void detach_factura_ventas(factura_venta entity)
		{
			this.SendPropertyChanging();
			entity.vendedor = null;
		}
	}
}
#pragma warning restore 1591
